#!/bin/bash -xv

VERSION=$1
ROOTDIR=$(git rev-parse --show-toplevel)

echo "POST Flow release finish version: $VERSION $2 $3 $4"

FILE=composer.json

if [ -f $FILE ]; then

    TYPE=$(jq -r '.type' $FILE)
    NAME=$(jq -r '.name' $FILE)
    SLUG=$(basename $NAME)

    if [ "$TYPE" = "wordpress-plugin" ] || [ "$TYPE" = "wordpress-theme" ]; then

	# Ensure we got required dependencies

	composer update --no-interaction --quiet

	# Create temporary dir

	TMPDIR=$(mktemp -d)
	mkdir -p $TMPDIR/$SLUG

	# Rsync working tree to temporary dir
	rsync -ar \
	      --quiet \
	      --delete-excluded \
	      --include="assets/scripts/vendor" \
	      --exclude="components" \
	      --exclude="vendor" \
	      --exclude="VERSION" \
	      --exclude=".git" \
	      --exclude=".sass-cache" \
	      --exclude=".gitignore" \
	      --exclude=".phpmd.xml" \
	      --exclude=".bowerrc" \
	      --exclude="assets/styles/*.scss" \
	      --prune-empty-dirs \
	      . $TMPDIR/$SLUG/

	# Regenerate vendor dir excluding development dependencies and do not run scripts
	composer update --working-dir $TMPDIR/$SLUG --no-interaction --no-dev --optimize-autoloader --no-scripts --quiet

	# Create distribution zip

	(
	    cd $TMPDIR
	    zip -9qr $ROOTDIR/../$SLUG.$VERSION.zip ./* \
		-x \
		$SLUG/*composer.*
	)

    fi

fi
